name: budget
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_card: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  vs_scrollbar: ^0.2.1
  flutter_masked_text: ^0.8.0
  password_strength: ^0.2.0
  cpf_cnpj_validator: ^2.0.0
  easy_mask: ^2.0.1
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  firebase_auth: ^3.0.1
  flutter_modular: ^3.3.1
  cloud_firestore: ^2.4.0
  shimmer: ^2.0.0

dev_dependencies:
  mobx_codegen: ^2.0.2
  build_runner: ^1.3.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf